### ISSUE TITLE
How big would be the image with pacman inside?

### ISSUE THREAD

**Issue by frol** [shuLhan/arch-docker#1]
I like the size of your arch-base image, but I would prefer to use Dockerfiles in a usual way, i.e. using pacman directly instead of maintaining custom images in custom scripts.

**Comment by shuLhan** [comment]
Here is the base image with pacman:

```
ms 0 % docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
sulhan/arch-base-pacman     latest              fc90a45c85cc        15 seconds ago      187.3 MB
sulhan/arch-base            latest              1200b31236ee        2 weeks ago         118.3 MB
```

with the following packages installed: acl archlinux-keyring attr bash bzip2 ca-certificates ca-certificates-cacert ca-certificates-mozilla ca-certificates-utils coreutils curl db e2fsprogs expat filesystem findutils gcc-libs gdbm glibc gmp gnupg gnutls gpgme gzip iana-etc keyutils krb5 less libarchive libassuan libcap libffi libgcrypt libgpg-error libidn libksba libldap libsasl libssh2 libtasn1 libutil-linux linux-api-headers lzo ncurses nettle npth openssl p11-kit pacman pacman-mirrorlist pcre perl pinentry readline sqlite texinfo tzdata xz zlib

Or you can try it yourself by copying `arch-base` to `arch-base-template`, and edit `vars.sh` which contain following content,

```
#!/bin/zsh
export HOSTNAME="arch-base"

PKGS=(pacman)
PKGS_REMOVED=()

IMAGE_NAME="sulhan/arch-base-pacman"
IMAGE_ARGS=()
```

**Comment by frol** [comment]
Oh, that becomes so much bigger; Arch definitely wasn't designed for small footprint :( (I was thinking about it in a context of using it instead of hacking glibc on Alpine Linux)

Thank you for your prompt answer! Great job, anyway!
